CREATE OR REPLACE TRIGGER TRG_PROCESO_PUNTAJE
AFTER INSERT ON PROCESO
FOR EACH ROW
DECLARE
CURSOR C_PROCESO IS SELECT v.id_region,PR.ID_FICHA,puntaje_total FROM PROCESO PR JOIN ficha_postulacion FP
ON pr.id_ficha=fp.id_ficha JOIN vivienda V
ON fp.rol_sii = v.rol_sii;
BEGIN
    FOR R_PRO IN C_PROCESO LOOP
    IF(R_PRO.ID_REGION IN (1) ) THEN
    UPDATE PROCESO P
    SET P.PUNTAJE_TOTAL = P.PUNTAJE_TOTAL*1.5
    where R_PRO.ID_FICHA = P.ID_FICHA;
    END IF;
    IF(R_PRO.ID_REGION IN (2) ) THEN
    UPDATE PROCESO P
    SET P.PUNTAJE_TOTAL = P.PUNTAJE_TOTAL*1.3
    where R_PRO.ID_FICHA = P.ID_FICHA;
    END IF;
    IF(R_PRO.ID_REGION IN (15) ) THEN
    UPDATE PROCESO P
    SET P.PUNTAJE_TOTAL = P.PUNTAJE_TOTAL*2
    where R_PRO.ID_FICHA = P.ID_FICHA;
    END IF;
    IF(R_PRO.ID_REGION IN (16) ) THEN
    UPDATE PROCESO P
    SET P.PUNTAJE_TOTAL = P.PUNTAJE_TOTAL*2.3
    where R_PRO.ID_FICHA = P.ID_FICHA;
    END IF;
    END LOOP;
END;